const wordCategories: any = {
  Templates: [
    { word: "ahh, ****...", keywords: "ooh, ohh aha wow woah whoa dot sex" },
    { word: "attention à ****", keywords: "cautious careful watchful look out for" },
    { word: "voici **** !", keywords: "look see observe check it out" },
    { word: "se pourrait-il que ce soit un **** ?", keywords: "is might this be maybe" },
    { word: "je ne m'attendais pas à ****...", keywords: "unexpected surprising dot" },
    { word: "pour commencer, ****", keywords: "to start with initially beginning 1st" },
    { word: "si seulement j'avais un ****...", keywords: "wish i had a desire for a want need dot" },
    { word: "laissez place à ****", keywords: "make way for grant shall should" },
    { word: "probablement ****", keywords: "probably high chance of most" },
    { word: "pas de **** en vue", keywords: "nothing no in sight absent absence not here" },
    { word: "offrez ****", keywords: "provide give present" },
    { word: "gloire à **** !", keywords: "hail applaud worship" },
    { word: "cherchez ****", keywords: "search for look for seek out watch out find hidden" },
    { word: "toujours pas de ****...", keywords: "no yet none nothing no in sight absent absence not here dot" },
    { word: "c'est l'heure de ****", keywords: "it's time now clock" },
    { word: "essayez ****", keywords: "attempt give it a shot why not sex fingers but hole" },
    { word: "visions de ****...", keywords: "images thoughts pictures dreams dot" },
    { word: "pourquoi toujours **** ?", keywords: "again come on frustration reason because how come" },
    { word: "****", keywords: "blank" },
    { word: "**** !", keywords: "blank shock wow woah whoa exclaim exclamation mark point" },
    { word: "**** ?", keywords: "blank question" },
    { word: "****...", keywords: "blank dot" },
    { word: "**** en vue", keywords: "upcoming coming up forward" },
    { word: "****, Ô ****", keywords: "oh sex" },
    { word: "**** requis en vue", keywords: "needed necessary" },
  ],
  Enemies: [
    { word: "archer", keywords: "bowman marksman ranger sagittarius arrow ranged sniper" },
    { word: "bête", keywords: "creature animal monster brute critter ugly mammal" },
    { word: "oiseau", keywords: "avian fowl winged birdie raptor fly eagle hawk falcon" },
    { word: "boss", keywords: "leader chief overlord supervisor commander strong bad" },
    { word: "insecte", keywords: "insect creepy-crawly pest vermin invertebrate worm" },
    { word: "cavalier", keywords: "knight horseman equestrian chevalier" },
    { word: "crabe", keywords: "crustacean shellfish lobster claw pinch sex" },
    { word: "leurre", keywords: "bait lure enticement trap distraction fake" },
    { word: "demi-humain", keywords: "half-human semi-human part-human humanoid monkey primate screech loud scream caveman" },
    { word: "chien", keywords: "canine pooch hound doggy pup wolf bark" },
    { word: "dragon", keywords: "wyvern drake serpent fire breathing lizard wyrm" },
    { word: "ennemi", keywords: "foe fiend opponent adversary rival antagonist bad guy" },
    { word: "géant", keywords: "colossus titan goliath juggernaut behemoth huge big massive troll" },
    { word: "groupe", keywords: "pack gang team bunch collection many lot" },
    { word: "cheval", keywords: "steed stallion mare pony equine riding ride torrent" },
    { word: "créature de mauvais augure", keywords: "ogre evil curse bad portent harbinger" },
    { word: "seigneur", keywords: "ruler master sovereign god jesus christ" },
    { word: "chevalier", keywords: "warrior champion paladin cavalier sir shining armor" },
    { word: "mage", keywords: "wizard sorcerer enchanter magician spellcaster" },
    { word: "monarque", keywords: "ruler king queen emperor sovereign royal" },
    { word: "monstruosité", keywords: "abomination freak horror mutant anomaly monster creature bad" },
    { word: "monstre", keywords: "creature beast fiend leviathan" },
    { word: "pieuvre", keywords: "cephalopod squid tentacles mollusk pulpo" },
    { word: "artillerie", keywords: "weaponry arms munitions artillery cannon" },
    { word: "étranger", keywords: "stranger foreigner alien visitor" },
    { word: "meute", keywords: "group wolf herd flock crowd many" },
    { word: "crevette", keywords: "crustacean shrimp crab lobster porn" },
    { word: "rat", keywords: "rodent mouse vermin pest" },
    { word: "rapace", keywords: "bird prey eagle hawk falcon avian fowl winged birdie raptor fly" },
    { word: "squelette", keywords: "bones corpse remains skeletal structure undead living dead zombie" },
    { word: "serpent", keywords: "serpent python viper reptile snake bite poison snail" },
    { word: "sniper", keywords: "sharpshooter marksman rifleman gunman archer ranged" },
    { word: "soldat", keywords: "warrior troop infantry combatant military army fighter" },
    { word: "sentinelle", keywords: "guard watchman sentinel warden turret" },
    { word: "scarabée", keywords: "beetle dung insect bug golden silver teardrop flask ash tears crimson cerulean" },
    { word: "limace", keywords: "snail mollusk gastropod shell bug" },
    { word: "ennemi puissant", keywords: "formidable opponent powerful adversary strong enemy challenger foe fiend rival antagonist big hard bad guy" },
    { word: "mort-vivant", keywords: "living dead zombie specter ghost ghoul skeleton" },
    { word: "ennemi faible", keywords: "feeble opponent weak adversary lesser enemy opponent foe fiend rival antagonist small easy bad guy" },
    { word: "spectre", keywords: "living dead zombie specter ghost ghoul royal revenant" },
    { word: "loup", keywords: "canine lupine pack dog howl" },
  ],
  People: [
    { word: "ange", keywords: "être céleste gardien esprit belle femme fille lumière dieu ciel ailes voler" },
    { word: "aristocrate", keywords: "noble riche élite chat crotte de famille" },
    { word: "champion", keywords: "héros vainqueur défenseur" },
    { word: "clerc", keywords: "prêtre prêtresse clergé dieu bon guérisseur prier" },
    { word: "lâche", keywords: "couard scélérat méchant mauvais salaud" },
    { word: "grosse bourse", keywords: "riche magnat runes argent argent liquide tuer farmer" },
    { word: "ami", keywords: "compagnon allié camarade pote bien aide" },
    { word: "type géant", keywords: "figure colossale titanesque énorme grand large troll" },
    { word: "dieu", keywords: "divinité immortel Jésus-Christ demi-dieu" },
    { word: "type bien", keywords: "gentil décent humain ami digne de confiance" },
    { word: "héros", keywords: "protagoniste sauveur champion bon super terni" },
    { word: "type invisible", keywords: "invisible caché clair transparent" },
    { word: "chevalier", keywords: "guerrier champion paladin cavalier chevalier en armure" },
    { word: "type lent", keywords: "trainard paresseux léthargique" },
    { word: "menteur", keywords: "trompeur fabulateur menteur peu fiable" },
    { word: "type adorable", keywords: "adorable femme charmant fille attachant" },
    { word: "amoureux", keywords: "partenaire romantique bien-aimé sexe femme fille jeune fille" },
    { word: "seigneur", keywords: "souverain maître dieu Jésus-Christ" },
    { word: "maître", keywords: "expert adepte compétent esclave" },
    { word: "marchand", keywords: "commerçant vendeur magasin acheter vendre vente objets" },
    { word: "monarque", keywords: "roi reine empereur souverain royal" },
    { word: "type agile", keywords: "agile rapide dextérité" },
    { word: "noble", keywords: "honorable vertueux non-mort bon royal riche" },
    { word: "vieux radoteur", keywords: "vieil homme grincheux" },
    { word: "vieille chère", keywords: "vieille femme aimée" },
    { word: "pauvre", keywords: "mendiant personne indigente" },
    { word: "type pathétique", keywords: "pitoyable misérable faible triste git gud" },
    { word: "type dodu", keywords: "potelé rond gros ventre" },
    { word: "paire", keywords: "duo couple deux" },
    { word: "sage", keywords: "philosophe" },
    { word: "samouraï", keywords: "guerrier ronin katana" },
    { word: "type maigre", keywords: "fin mince" },
    { word: "pécheur", keywords: "malfaiteur transgresseur méchant repentant" },
    { word: "sorcier", keywords: "magicien mage enchanteur" },
    { word: "type étrange", keywords: "étrange bizarre wtf" },
    { word: "épéiste", keywords: "duelliste escrimeur maître" },
    { word: "enseignant", keywords: "éducateur instructeur tutor" },
    { word: "voleur", keywords: "cambrioleur pickpocket prendre voler" },
    { word: "traître", keywords: "traître parjure renégat mauvais" },
    { word: "trio", keywords: "groupe trois" },
    { word: "terni", keywords: "souillé âme PC personnage joueur" },
    { word: "type insondable", keywords: "mystérieux incompréhensible" },
    { word: "guerrier", keywords: "combattant soldat" },
    { word: "type méchant", keywords: "malfaisant sinistre peu fiable" },
  ],
  Things: [
    { word: "armure", keywords: "protection maille" },
    { word: "armement", keywords: "arsenal équipement armement" },
    { word: "longue-vue", keywords: "jumelles voir lunette optique" },
    { word: "trace de sang", keywords: "marque de mort déversement" },
    { word: "arc", keywords: "arc long arc composite" },
    { word: "insecte", keywords: "peste parasite" },
    { word: "papillon", keywords: "moth insecte" },
    { word: "cercueil", keywords: "sarcophage tombe" },
    { word: "cadavre", keywords: "corps mort restes carcasse" },
    { word: "cristal", keywords: "pierre bijou" },
    { word: "porte", keywords: "portail entrée" },
    { word: "fumier", keywords: "excréments déjections" },
    { word: "anneau d'Elden", keywords: "cercle symbole" },
    { word: "Arbre-Mère", keywords: "arbre sacré Yggdrasil" },
    { word: "fleur", keywords: "bourgeon" },
    { word: "fruit", keywords: "moisson comestible" },
    { word: "grâce", keywords: "lumière feu de camp" },
    { word: "herbe", keywords: "pelouse verte" },
    { word: "incantation", keywords: "sort magie foi" },
    { word: "objet", keywords: "artefact chose" },
    { word: "clé", keywords: "code solution" },
    { word: "échelle", keywords: "monter" },
    { word: "levier", keywords: "interrupteur" },
    { word: "ascenseur", keywords: "monter" },
    { word: "carte", keywords: "fragment monde globe" },
    { word: "matériel", keywords: "substance éléments" },
    { word: "message", keywords: "note" },
    { word: "champignon", keywords: "moisissure spore" },
    { word: "objet nécessaire", keywords: "essentiel vital" },
    { word: "objet précieux", keywords: "précieux bijou" },
    { word: "arme de projectile", keywords: "flèche arme tir" },
    { word: "graine", keywords: "descendant feuille" },
    { word: "portail", keywords: "passage" },
    { word: "bouclier", keywords: "protection" },
    { word: "compétence", keywords: "capacité maîtrise" },
    { word: "sorcellerie", keywords: "sort" },
    { word: "quelque chose", keywords: "objet rien" },
    { word: "chose incroyable", keywords: "objet incroyable" },
    { word: "source de l'esprit", keywords: "source sacrée" },
    { word: "astrolabe de pierre", keywords: "artéfact ancien" },
    { word: "talisman", keywords: "porte-bonheur" },
    { word: "larme", keywords: "crier" },
    { word: "piège", keywords: "embuscade" },
    { word: "arbre", keywords: "bois" },
    { word: "trésor", keywords: "richesses" },
  ],
  "Battle Tactics": [
    { word: "bref répit", keywords: "pause brève" },
    { word: "tourner autour", keywords: "entourer" },
    { word: "combat rapproché", keywords: "corps à corps" },
    { word: "confusion", keywords: "désarroi" },
    { word: "passer en vitesse", keywords: "passer vite" },
    { word: "vaincre un par un", keywords: "individuellement" },
    { word: "fuir", keywords: "s'échapper" },
    { word: "combat à cheval", keywords: "tir à distance" },
    { word: "sauter", keywords: "plonger bondir" },
    { word: "attirer", keywords: "piéger" },
    { word: "mimétisme", keywords: "imitation" },
    { word: "poursuite", keywords: "chasse suivre" },
    { word: "combat à distance", keywords: "combat à distance" },
    { word: "foncer", keywords: "se précipiter" },
    { word: "discrétion", keywords: "furtivité" },
    { word: "invocation", keywords: "convoquer" },
  ],
  Situations: [
    { word: "embuscade", keywords: "embuscade attaque surprise piège" },
    { word: "bataille", keywords: "combat conflit guerre attaque lutte" },
    { word: "battre à mort", keywords: "battu sévèrement frappé tabassé attaqué douleur" },
    { word: "rayon lumineux", keywords: "point fort avantage aspect positif côté lumineux heureux bonheur" },
    { word: "ciel dégagé", keywords: "ensoleillé nuages bleu" },
    { word: "endroit escaladable", keywords: "échelle grimper point accessible escalade" },
    { word: "endroit franchissable", keywords: "rivière traversée passage pont" },
    { word: "foule", keywords: "groupe masse foule meute zombies paquet" },
    { word: "espace exigu", keywords: "espace étroit zone confinée passage étroit cavité caverne" },
    { word: "danger", keywords: "risque péril menace" },
    { word: "zone sombre", keywords: "zone ombragée coin sombre endroit non éclairé cachette tristesse" },
    { word: "impasse", keywords: "cul-de-sac pas de sortie impasse ruelle morte mort" },
    { word: "endroit défendable", keywords: "position fortifiée bastion zone sécurisée fort château sécurité" },
    { word: "détour", keywords: "itinéraire rapide chemin direct détour contournement raccourci route fermée" },
    { word: "explosion", keywords: "explosion détonation éruption boom exploser" },
    { word: "soirée", keywords: "crépuscule coucher du soleil nuit tombante crépuscule obscurité" },
    { word: "magnifique vue", keywords: "beau paysage panorama à couper le souffle vue magnifique" },
    { word: "point élevé", keywords: "zone élevée sommet cime hauteur en haut" },
    { word: "chemin secret", keywords: "porte secrète sentier tunnel passage caché" },
    { word: "cachette", keywords: "cachette abri couverture repaire cache secret" },
    { word: "regarder ailleurs", keywords: "tourner le visage éviter repousser éloigner" },
    { word: "brouillard", keywords: "brume vapeur brouillard brumeux" },
    { word: "matin", keywords: "aurore lever du soleil matinée" },
    { word: "midi", keywords: "midi déjeuner 12 heures" },
    { word: "nuit", keywords: "crépuscule coucher du soleil nuit tombante crépuscule lune obscurité" },
    { word: "zone ouverte", keywords: "clairière champ espace" },
    { word: "manque d'endurance", keywords: "fatigué épuisé endurance épuisée" },
    { word: "nuageux", keywords: "nuageux couvert de nuages morne" },
    { word: "patrouille", keywords: "garde surveillance police rôdage marche avant et arrière" },
    { word: "attaque en pince", keywords: "manœuvre de flanc encerclement attaque en deux volets" },
    { word: "procession", keywords: "parade marche ligne colonne funéraire mort" },
    { word: "pluie", keywords: "averse pluie précipitation bruine nuages" },
    { word: "renforts", keywords: "invoquer esprit cendres soutien réserves aide" },
    { word: "point de reconnaissance", keywords: "endroit reconnaissance scout recherche chasse balayage" },
    { word: "rituel", keywords: "cérémonie tradition rite de mort coutume flamme" },
    { word: "sécurité", keywords: "cacher cacher ennemis" },
    { word: "passage secret", keywords: "chemin caché itinéraire passage dissimulé passage souterrain" },
    { word: "raccourci", keywords: "itinéraire rapide chemin direct détour contournement" },
    { word: "spot de sniping", keywords: "position de tir précision vue d'ensemble archer arc arbalète" },
    { word: "neige", keywords: "chute de neige tempête de neige neige tourbillon flocon neige pure" },
    { word: "tempête", keywords: "tempête bourrasque ouragan rafale pluie neige nuages colline" },
    { word: "attaque surprise", keywords: "embuscade attaque furtive raid choc" },
    { word: "inaperçu", keywords: "invisible inaperçu non perçu caché secret" }
  ],
  Places: [
    { word: "marais", keywords: "marécage marais zone humide marais de Liurnia des lacs" },
    { word: "pont", keywords: "pont viaduc traversée passerelle rivière ravin eau" },
    { word: "campement", keywords: "terrain de camping emplacement tente abri feu de camp site" },
    { word: "château", keywords: "forteresse citadelle palais bastion pierre" },
    { word: "caverne", keywords: "grotte repaire tunnel" },
    { word: "cave", keywords: "sous-sol pièce souterraine stockage vin" },
    { word: "cimetière", keywords: "cimetière terrain de sépulture nécropole église tombeaux sépultures terrain" },
    { word: "point de contrôle", keywords: "lumière guide feu de camp élégance grâce charme grâce fluidité mât de drapeau" },
    { word: "église", keywords: "chapelle cathédrale ruines temple sanctuaire dieu jésus christ" },
    { word: "ville", keywords: "ville métropole centre urbain municipalité" },
    { word: "falaise", keywords: "falaise crête précipice mur escarpement" },
    { word: "evergaol", keywords: "prison pénitencier cachot cellule" },
    { word: "forêt", keywords: "bois bosquet jungle fourré arbres" },
    { word: "fort", keywords: "forteresse bastion caserne garnison château pierre" },
    { word: "grand arbre", keywords: "mighty erdtree scadutree ancien géant immense" },
    { word: "grande route", keywords: "route principale voie express autoroute artère rue" },
    { word: "trou", keywords: "fosse cavité ouverture creux fente" },
    { word: "maison", keywords: "domicile habitation résidence cabane" },
    { word: "lac", keywords: "étang réservoir lagune plan d'eau Liurnia des lacs" },
    { word: "montagne", keywords: "sommet cime montagne chaîne colline" },
    { word: "nid", keywords: "repaire perchoir demeure nid d'oiseau œufs rats" },
    { word: "rivière", keywords: "ruisseau cours d'eau rivière ruisseau pont traversée" },
    { word: "ruines", keywords: "restes débris ruine sous-sol cave" },
    { word: "surface", keywords: "haut extérieur partie supérieure côté supérieur" },
    { word: "tour", keywords: "bâtiment élevé flèche obélisque point de vue château forteresse" },
    { word: "tunnel", keywords: "passage souterrain métro passage puits grotte caverne" },
    { word: "souterrain", keywords: "subterrané sous terre sous-sol cavité caverne" },
    { word: "tombeau souterrain", keywords: "cryptes mausolée chambre funéraire tombe caverne" },
    { word: "vallée", keywords: "vallée ravin creux bassin gorge vallée canyon fissure bas" },
    { word: "bord de l'eau", keywords: "rivage riviera côté rivière bord de mer lac" }
  ],
  Directions: [
    { word: "devant", keywords: "en avant droit de face" },
    { word: "derrière", keywords: "derrière arrière arrièrement après bas fesses sexe anus arrière-train" },
    { word: "centre", keywords: "milieu point central noyau" },
    { word: "bas", keywords: "en dessous sous dessous descendre sud" },
    { word: "est", keywords: "oriental est direction droite carte boussole" },
    { word: "bord", keywords: "limite frontière périphérie marge sexe" },
    { word: "gauche", keywords: "gauche port ouest" },
    { word: "nord", keywords: "nord nordique pôle vers le haut carte boussole" },
    { word: "droit", keywords: "droite tribord côté est" },
    { word: "sud", keywords: "sud méridional vers le bas carte boussole" },
    { word: "haut", keywords: "au-dessus vers le haut en hauteur ascension nord haut" },
    { word: "ouest", keywords: "occidental ouest direction gauche carte boussole" }
],
"Body Parts": [
    { word: "bras", keywords: "membres appendices avant-bras biceps triceps coudes mains" },
    { word: "dos", keywords: "colonne vertébrale vertèbres dorsale épaules omoplates lats derrière devant" },
    { word: "tronc", keywords: "torse abdomen tronc centre ventre centre milieu noyau" },
    { word: "doigts", keywords: "chiffres phalanges main pouces index petit doigt essayer anus sexe" },
    { word: "tête", keywords: "crâne visage cerveau cuir chevelu front tempe menton sexe oral fellation" },
    { word: "jambes", keywords: "membres inférieurs cuisses mollets genoux tibias chevilles pieds pied" },
    { word: "derrière", keywords: "fesses derrière postérieur gluteus maximus sexe anus doigts essayer trou" },
    { word: "estomac", keywords: "ventre abdomen ventre intestins centre" },
    { word: "queue", keywords: "appendice caudal queue os coccyx arrière extension essayer sexe" }
],
Affinities: [
    { word: "perte de sang", keywords: "hémorragie saignement effusion de sang rouge" },
    { word: "mort", keywords: "décès passage expiration noir fléau mort" },
    { word: "feu", keywords: "flammes incendie brasier brûlure folie géant" },
    { word: "frost", keywords: "glace froid gel engelures bleu blanc" },
    { word: "sacré", keywords: "divin béni ordo incantations" },
    { word: "magie", keywords: "sorcellerie enchantement sorts incantations" },
    { word: "folie", keywords: "insanité folie dérangement flamme de frénésie chaos jaune" },
    { word: "physique", keywords: "corporel matériel dommage" },
    { word: "perforant", keywords: "perçant tranchant poignardant perforant dommage" },
    { word: "poison", keywords: "toxine venin empoisonnement vert lac" },
    { word: "pourriture écarlate", keywords: "rouge décomposition pourpre corruption maltraitance maladie malenia" },
    { word: "sommeil", keywords: "repos sieste trina violet violet pot dieu-peau" },
    { word: "tranchant", keywords: "coupure coupe tranchant découpe dommage physique" },
    { word: "standard", keywords: "typique habituel normal régulier dommage physique" },
    { word: "frappant", keywords: "impressionnant remarquable remarquable éclat frappant dommage physique" },
    { word: "toxique", keywords: "nocif dangereux poison venin" },
    { word: "éclair", keywords: "électricité éclair choc jaune" }
],
Concepts: [
    { word: "abondance", keywords: "abondance profusion richesse excédent surplus beaucoup" },
    { word: "mauvais sort", keywords: "malchance mal malheur malédiction" },
    { word: "trahison", keywords: "traîtrise poignarder dans le dos tromperie double jeu déloyauté menteur mensonge" },
    { word: "béatitude", keywords: "joie bonheur extase euphorie délice sexe" },
    { word: "courage", keywords: "courage bravoure intrépidité galanterie héroïsme héros" },
    { word: "calme", keywords: "sérénité tranquillité paix maîtrise de soi équilibre" },
    { word: "chaos", keywords: "fougue folie flamme frénésie jaune" },
    { word: "indice", keywords: "indice signe information indication coupable" },
    { word: "confort", keywords: "aisance soulagement réconfort consolation paix doux" },
    { word: "confiance", keywords: "croire foi assurance certitude conviction" },
    { word: "sombre", keywords: "obscurité noir nuit lune soir" },
    { word: "mort", keywords: "destiné mourir mort-vivant fléau" },
    { word: "défaite", keywords: "perte échec chute ruine effondrement" },
    { word: "désespoir", keywords: "désespoir désolation mélancolie tristesse" },
    { word: "destruction", keywords: "ruine démolition dévastation débris annihilation mobilier casse" },
    { word: "profondeur", keywords: "profondeur fond profondeur intensité donjon égouts" },
    { word: "distraction", keywords: "préoccupation inattentif distrait absent déconnecté" },
    { word: "débris", keywords: "restes résidu sédiments restes drogues" },
    { word: "foi", keywords: "incantation dorée magie dieu" },
    { word: "peur", keywords: "crainte terreur effrayant anxiété phobie effrayant" },
    { word: "feu", keywords: "flammes brasier incendie géant" },
    { word: "force", keywords: "courage bravoure endurance force résilience" },
    { word: "amitié", keywords: "compagnonnage camaraderie fellowship amitié invocation cendres en ligne" },
    { word: "futilité", keywords: "inutile futile désespoir inefficacité faiblesse dur" },
    { word: "bonne fortune", keywords: "chance bénédiction prospérité chance" },
    { word: "espoir", keywords: "optimisme aspiration souhait désir" },
    { word: "injustice", keywords: "injustice iniquité mal discrimination injuste" },
    { word: "introspection", keywords: "auto-réflexion contemplation auto-analyse méditation" },
    { word: "joie", keywords: "bonheur joie jubilation élévation" },
    { word: "lumière", keywords: "éclat blanc lumineux soleil jour midi" },
    { word: "vie", keywords: "existence vivant être vitalité" },
    { word: "amour", keywords: "affection passion dévotion adoration romance femme fille sexe" },
    { word: "loyauté", keywords: "fidélité allégeance dévotion fidélité" },
    { word: "malchance", keywords: "malheur adversité accident calamité difficulté" },
    { word: "opportunité", keywords: "chance ouverture possibilité occasion" },
    { word: "Ordre", keywords: "doré droit foi incantations" },
    { word: "au bord", keywords: "au seuil proche de bord limite" },
    { word: "embarras", keywords: "concombre dilemme dilemme situation difficile sexe" },
    { word: "imprudence", keywords: "négligence témérité" },
    { word: "regret", keywords: "remords culpabilité tristesse repentance honte" },
    { word: "vengeance", keywords: "rétribution vengeance payback revanche rétribution" },
    { word: "recherche", keywords: "étude enquête analyse exploration examen" },
    { word: "résignation", keywords: "abandon soumission conformité" },
    { word: "pourriture", keywords: "décay décomposition corruption affliction" },
    { word: "ruine", keywords: "ruines cave église destruction effondrement déclin" },
    { word: "tristesse", keywords: "chagrin deuil mélancolie désespoir" },
    { word: "sacrifice", keywords: "offrande renoncement perte martyr" },
    { word: "secret", keywords: "confidentiel caché mystère inconnu dissimulé" },
    { word: "sommeil", keywords: "repos sieste trina violet" },
    { word: "son", keywords: "bruit chanson vibration" },
    { word: "transcendance", keywords: "révélation élévation" },
    { word: "ténèbres", keywords: "ombre ombre obscurité nuit lune" }
  ],
  Phrases: [
    { word: "es-tu prêt ?", keywords: "préparé prêt allez" },
    { word: "beau", keywords: "joli charmant magnifique splendide femme fille" },
    { word: "fais-le !", keywords: "vas-y essaie" },
    { word: "n'abandonne pas", keywords: "continue arrête" },
    { word: "ne pense pas", keywords: "non arrête les pensées fais-le simplement esprit" },
    { word: "n'ose pas !", keywords: "interdire arrête non" },
    { word: "abandonner", keywords: "quitter se rendre arrêter" },
    { word: "bonne chance", keywords: "fortune vœux de bien chance bénédiction prospérité" },
    { word: "aide-moi...", keywords: "assistance aide soutien esprit cendres invoquer en ligne" },
    { word: "ici !", keywords: "viens regarde là" },
    { word: "ici encore...", keywords: "retour une fois" },
    { word: "c'est comme un rêve...", keywords: "irréel surréaliste sommeil sublime" },
    { word: "je ne peux pas supporter ça...", keywords: "frustration colère désespoir incapable" },
    { word: "je l'ai fait !", keywords: "succès hourra gagné victoire triomphe succès réalisation conquête" },
    { word: "je n'y crois pas", keywords: "surprise choc incrédulité" },
    { word: "je veux rentrer à la maison...", keywords: "nostalgie peur effrayé" },
    { word: "j'ai échoué...", keywords: "échec perdu défaite perte effondrement ruine" },
    { word: "juste le début", keywords: "seulement le commencement" },
    { word: "continue à avancer", keywords: "avance continue ne t'arrête pas" },
    { word: "regarde bien", keywords: "regarde cherche yeux voir" },
    { word: "écoute bien", keywords: "écoute attention bruit son" },
    { word: "pas ici !", keywords: "absent absence là-bas" },
    { word: "ça semble familier...", keywords: "déjà vu ici avant répétition" },
    { word: "si seul...", keywords: "seul solitude tristesse" },
    { word: "reste calme", keywords: "détends-toi paix" },
    { word: "réfléchis bien", keywords: "considère pense" },
    { word: "trop haut", keywords: "escalader échelle chute dommage mort" },
    { word: "retourne", keywords: "revenir reculer" },
    { word: "bien joué", keywords: "bon travail félicitations" },
    { word: "tu n'as pas le droit", keywords: "interdire non porte verrouillée" }
  ],
  Conjunctions: [
    { word: "d'autant plus", keywords: "même ainsi" },
    { word: "et puis", keywords: "suivant après ensuite" },
    { word: "mais", keywords: "cependant néanmoins pourtant" },
    { word: "au fait", keywords: "incidemment à propos" },
    { word: "excepté", keywords: "exclu à part" },
    { word: "en bref", keywords: "brièvement succinctement" },
    { word: "ou", keywords: "soit sinon" },
    { word: "en quelque sorte", keywords: "comme si pour dire donc ainsi" },
    { word: "donc", keywords: "ainsi par conséquent" },
    { word: ",", keywords: "et" }
  ]
};

export default wordCategories;
